### PR TITLE
Hide right-side tab shadow

### PR DESCRIPTION
**Pull request by dimateos**
Fix mentioned in https://github.com/mondersky/tabscolor-vscode/issues/39
- I think removing it is simpler
- but maybe some people may want to keep it even when colored wrong?

### CODE REVIEW

**Comment by dimateos** [comment]
The numbers? In my case they are still visible, but there might be issues with some other decorators too, thanks for testing.
Here I have ALL default extensions and settings + `"workbench.editor.tabSizing": "shrink",`:

2024-10-22_(172923)_Code

> Btw I'm just editing the inject.css not building the extension could that affect?

**Comment by mondersky** [comment]
may I suggest
`.tab .monaco-icon-label-container:after, .tab .monaco-icon-name-container:after{background:transparent !important;}`

**Comment by dimateos** [comment]
Both selectors work for me. Are the error counters still hidden for you?

The shadow appearing on hover was due to a theme that was setting `"tab.hoverForeground"`. I guess we could try to find the appropriate selector but the user could also override the value inside their `"workbench.colorCustomizations"`

**Comment by mondersky** [comment]
the background rule does a perfect job for me, as for the hover issue, it is better if we can overwrite the rule using css that way the user won't have to do any extra step

**Comment by dimateos** [comment]
I currently have a better solution which sets the color following user settings instead of transparent to support the fading on shrinked tabs.

    .tab[title*="\\vscode-tabscolor" i] .monaco-icon-label-container::after {
        background: linear-gradient(to left, #8E2881, transparent) !important;
    }
    ...

But I have bad news about overriding the user theme or workbench.colorCustomizations.
Some colors such as the hovered tab background are set using `!important` already, and with a very specific selector!
I have a WIP set of selectors that work but are quite long in order to beat that specificify...

image

Btw you can try setting all these tab background colors to see what could fail depending on the theme/user.
For me, with the current extension, all hovering colors fail and depending on `"workbench.editor.tabSizing"` you get the shadows.

    "workbench.colorCustomizations": {
        "tab.activeBackground": "red",
        "tab.hoverBackground" : "red",
        "tab.unfocusedHoverBackground" : "red",
        "tab.inactiveBackground" : "red",
        "tab.selectedBackground" : "red",
        "tab.unfocusedActiveBackground" : "red",
        "tab.unfocusedInactiveBackground" : "red",
        // foreground could also fail tho...
    }

**Comment by mondersky** [comment]
The new selector is indeed more specific and if it keeps the shade then it is a good approach. As for the hover color, I tested the settings you shared and understand your concern. The outcome isn’t ideal, but writing lengthy selectors just to override !important could make the CSS harder to maintain and increase the risk of issues if the HTML structure changes even slightly in the future. I don’t think this is a major problem in this context, so after reconsideration I’d suggest asking the user to take an extra step instead. Since only a minority of users will likely need this, we could detect if these settings are applied and then prompt the user with an alert to notify them of the potential conflict with our CSS rules. And maybe even ask to clear those settings for them automatically with a button (if this is allowed by the API). What do you think ?

**Pull request merged**
